lobal:
  scrape_interval:     10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus-vian'
    static_configs:
    - targets: ['10.13.13.10:9090']

  - job_name: 'node-vian'
    scrape_interval:  5s
    static_configs:
    - targets: ['10.13.13.10:9100','10.13.13.20:9100']

  - job_name: 'docker-vian'
    static_configs:
    - targets: ['10.13.13.10:9323']

  - job_name: 'mysql-vian'
    scrape_interval:  5s
    static_configs:
    - targets: ['10.13.13.10:9104']

  - job_name: 'cadvisor-vian'
    static_configs:
    - targets: ['10.13.13.10:8080']

  - job_name: 'apache-vian'
    static_configs:
    - targets: ['10.13.13.10:9117','10.13.13.20:9117']

  - job_name: 'haproxy-vian'
      static_configs:
    - targets: ['10.13.13.10:8404']

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 10.13.13.10:9093

rule_files:
  - "web_rules.yml"